AMPLITUDE      = 1
ENERGY         = 2
COUNTS         = 3
DURATION       = 4
RMS            = 5
ASL            = 6
THRESHOLD      = 7
RISETIME       = 8
COUNTS_TO_PEAK = 9
AVGFREQ        = 10
REV_FREQ       = 11
INIT_FREQ      = 12
SIG_STRENGTH   = 13
ABS_ENERGY     = 14
TIME           = 15
CHANNEL        = 16
PART_POWERS    = 17
FREQPP1        = 18
FREQPP2        = 19
FREQPP3        = 20
FREQPP4        = 21
FREQCENT       = 22
FREQPEAK       = 23
PARAM1         = 30
PARAM2         = 31
PARAM3         = 32
PARAM4         = 33
PARAM5         = 34
PARAM6         = 35
PARAM7         = 36
PARAM8         = 37
CYCLES         = 38
MAX_FREATURES  = CYCLES+1
GOOD	       = 0


STREAMTRIG_EXT     =  1   # external input triggers all streaming channels
STREAMTRIG_HIT     =  2   # hit on any stream channel causes all to stream
STREAMTRIG_TIMED   =  4   # automatic streaming after an interval has elapsed (start times are a multiple of this #)
STREAMTRIG_USER    =  8   # ignored by low end, high end must start the trigger when F11 is pressed
STREAMING_USER_END = 16   # true streaming (PCole's definition), user starts and ends, only valid with STREAMTRIG_USER
